default_context:
  project_name: 'OpenAdapt MarketPlace'
  project_slug: 'openadapt-marketplace'
  domain_main: 'openadapt-marketplace.com'
  domain_staging: 'stag.openadapt-marketplace.com'
  docker_swarm_stack_name_main: 'openadapt-marketplace-com'
  docker_swarm_stack_name_staging: 'stag-openadapt-marketplace-com'
  secret_key: '8a7f9de46fcc77d1854b682a93551a8ba8f218419ba8b95e74b5cb01d8cc339d'
  first_superuser: 'admin@openadapt-marketplace.com'
  first_superuser_password: '9a5d8875797fa00e3a272f4fd7407aedb7d0547b00f72482f8a9dc88ecdd8dd2'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.openadapt-marketplace.com", "https://stag.openadapt-marketplace.com", "https://openadapt-marketplace.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@openadapt-marketplace.com'
  postgres_password: '17228a720760af8ea86181af486c4d146ee4f72da55bf4f117d476e3b5584416'
  pgadmin_default_user: 'admin@openadapt-marketplace.com'
  pgadmin_default_user_password: '9a5d8875797fa00e3a272f4fd7407aedb7d0547b00f72482f8a9dc88ecdd8dd2'
  traefik_constraint_tag: 'openadapt-marketplace.com'
  traefik_constraint_tag_staging: 'stag.openadapt-marketplace.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:9a5d8875797fa00e3a272f4fd7407aedb7d0547b00f72482f8a9dc88ecdd8dd2'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
